---

- name: docker-rsyslog restart
  service:
    name: rsyslog
    state: restarted
  when: (not docker_role_debug|bool)

- name: docker restart
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
  when: (not docker_role_debug|bool)
