---

- name: docker-rsyslog restart
  service:
    name: rsyslog
    state: restarted
  ignore_errors: docker_role_debug | bool

- name: docker restart
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
  ignore_errors: docker_role_debug | bool
